### ISSUE TITLE
Pop-Gwas not working

### ISSUE THREAD

**Issue by lisaeick** [qlu-lab/POP-TOOLS#1]
Dear Pop-GWAS team
I tried your method in Finngen for a binary trait (CHD) which we do predict and making a continous GWAS using the probability values which the model outputs. The PopGWAS output is very inflated and very noisy.
We exchanged the LDSC reference file to a finngen specific one and the inflation got better but the noisyness remains.
Any ideas what went wrong?
![POP_GWAS_BIN_EUR](https://github.com/qlu-lab/POP-TOOLS/assets/70900052/ba0ffdee-a02a-48fc-a668-dff31f9ec3dc)

**Comment by jmiao24** [comment]
Hi lisaeick,

Thank you for your interest in POP-GWAS and for trying it out!

There are two scenarios where the current POP-GWAS may produce noisy results:
1. When there is sample overlap (or overlap of related samples) between labeled data and unlabeled data.
2. There is selection bias for the sample that are labeled (i.e., have observed CHD) compared with unlabeled data. This will make gwas-yhat-unlab to be different from gwas-yhat-lab.

Can you run the following sensitivity analysis to verify this?
- For 1, run a bivariate LDSC between gwas-yhat-unlab and gwas-yhat-lab, and between gwas-yhat-unlab and gwas-y-unlab. Check if the intercept is significantly different from zero.
- For 2, run a bivariate LDSC between gwas-yhat-unlab and gwas-yhat-lab. Check if they have close heritability and genetic correlation close to 1.

It would be great if you could also share the summary statistics with us via e-mail,  so we could reproduce your results and help in investigating the issue further. However, we understand if sharing this data is not feasible.

Best,
Jiacheng

**Comment by lisaeick** [comment]
Hey Jiacheng,

Thanks for your fast reply and sorry for needing much time to answer, but with our download boundaries and easter it took me some time to get the sumstats.

If you know a way to share them (since they are big) let me know. (2.2gb)

I prepared the data exclusively for popgwas and split them randomly in labeled and unlabeled so there is no selection bias. Of course there is relation within the samples, since its one cohort, but also we were sure to avoid sample overlap.

I downloaded the pure sumstats and attached the rsids, to avoid that one of my preprocessing steps might be the error.
As said please let me know how you would receive them and I am happy to share the sumstats.

Best Greetings
Lisa
________________________________

**Comment by lisaeick** [comment]
Hey Jiacheng,

Thanks for your fast reply and sorry for needing much time to answer, but with our download boundaries and easter it took me some time to get the sumstats.

If you know a way to share them (since they are big) let me know. (2.2gb)

I prepared the data exclusively for popgwas and split them randomly in labeled and unlabeled so there is no selection bias. Of course there is relation within the samples, since its one cohort, but also we were sure to avoid sample overlap.

I downloaded the pure sumstats and attached the rsids, to avoid that one of my preprocessing steps might be the error.
As said please let me know how you would receive them and I am happy to share the sumstats.

Best Greetings
Lisa

**Comment by jmiao24** [comment]
Hi Lisa,

Thank you for your email and for preparing the summary statistics.

Regarding the sharing of the large dataset, we can consider using cloud storage services Google Drive, Dropbox or OneDrive or Box. you can upload the data to a shared folder and provide me with a link to access it directly through e-mail (not through the Github issue). After that, I will look into POP-GWAS.

Best,
Jiacheng

**Comment by lisaeick** [comment]
Hi Jiacheng,

Can you please provide an email, other then this github thread so I can share the one Drive link?

Best
Lisa
________________________________

**Comment by jmiao24** [comment]
My e-mail is jiacheng.miao@wisc.edu

Best,
Jiacheng

**Comment by lisaeick** [comment]
hey Jiacheng,
I send you a share message via OneDrive.
Please let me know if there are problems occuring.
Thanks for your fast and friendly replies and best greetings
Lisa
________________________________

**Comment by jmiao24** [comment]
Hi Lisa,

Thank you for your patience. I have made two updates to POP-GWAS to resolve this issue:

1. removed SNPs with duplicate IDs.
2. added a flag in POP-GWAS to use sample overlap correction.

For 1, the original GWAS statistical summary had many SNPs with duplicate IDs, which would have messed up the calculations. 

For 2, although there are no overlapping individuals in the labeled and unlabeled data, the non-zero intercept (0.15) of the bivariate LDSC between input GWAS indicates that there is a residual correlation, and the GWAS performed in these two samples cannot be considered truly independent. I have added a version to address this issue. 

All you need to do is add `--sample-overlap` to the POP-GWAS script. You may also need to update your POP-GWAS dependencies to the latest version.

A Manhattan plot (without MAF cutoff) using the updated POP-GWAS is attached:
![Manhattan_no_qc](https://github.com/qlu-lab/POP-TOOLS/assets/56059516/1947c055-690b-4a05-9cb3-b7684921d79e)

If the MAF > 0.01 cutoff is applied, the Manhattan plot is
![Manhattan_with_qc](https://github.com/qlu-lab/POP-TOOLS/assets/56059516/1e03a5a1-61e4-4397-aa7a-6a44e8a3b3d3)

I have also emailed you the scripts to reproduce my results. Thank you for identifying the issues.

Best,
Jiacheng
