### ISSUE TITLE
reference allele

### ISSUE THREAD

**Issue by Afreen89** [qlu-lab/POP-TOOLS#2]
Hello, 
this might be something already mentioned somewhere, but I couldn't find it, so I am asking here.

I have the output from POP-GWAS, in the output there is A1 and A2 alleles. Could you tell me which of these is reference allele?

Apologies if it was something very obvious, I am new to the field. 

Awaiting your response. 
Afreen

**Comment by jmiao24** [comment]
Hi Afreen,

Thanks for your interest in POP-GWAS!

In the output from POP-GWAS, A1 represents the effect allele (i.e., the count of this allele is used in GWAS analyses and correspond to the sign of the BETA coefficient), while A2 is the non-effect allele. There isn't a direct correspondence between the A1 and A2 alleles in POP-GWAS's output and the reference allele. To interpret GWAS results, effect allele is typically more informative than reference allele.

The reference allele is the version of the allele that serves as a standard for comparisons against other alleles at the same locus. Typically, but not always, it's the most common allele found in a reference population (therefore it is possible to use EAF to get the reference allele). That being said, if you need to identify the reference allele, I recommend aligning the POP-GWAS summary statistics with a reference panel.

Best,
Jiacheng
