### ISSUE TITLE
Rare variants?

### ISSUE THREAD

**Issue by robchiral** [qlu-lab/POP-TOOLS#3]
Does this method work for rare variants (MAF < 0.01 or 0.001) from exome data using the genetic correlation estimated from GWAS common variants? I am getting strange results where the most significant POP-GWAS variants are highly significant for y_lab but generally not very significant for y_hat_lab or y_hat_unlab.

**Comment by robchiral** [comment]
Here is example data for some rare variants where genetic correlation between y_lab and y_hat_lab is 0.73 in GWAS data, N_lab ~ 35000, and N_unlab ~ 360000.

<img width="785" alt="image" src="https://github.com/user-attachments/assets/a0fb0803-325b-4f77-a4a1-01a851ffcd47">

**Comment by jmiao24** [comment]
Hi robchiral,

Thanks for your interest in POP-GWAS!

Could you please describe how you conducted the POP-GWAS analysis on rare variants? Did you input the summary statistics for rare variants as y_lab, y_hat_lab, and y_hat_unlab in the POP-GWAS script?

Best,
Jiacheng

**Comment by robchiral** [comment]
Hi Jiacheng,

Yes, I double checked that I am using the script correctly with y_lab, y_hat_lab, y_hat_unlab for the rare variant summary statistics. Only I am supplying --r 0.73 I calculated using LDSC for common variant (MAF > 0.01) summary statistics for g y_lab and y_hat_lab.

Best,
Robert

**Comment by jmiao24** [comment]
Thanks for clarifying, Robert! 

POP-GWAS uses phenotypic correlation (instead of genetic correlation) to linearly combine three summary statistics. The intercept of the bivariate LDSC is an estimate of the phenotypic correlation. So, could you try supplying --r with the intercept of the bivariate LDSC for the common variant (MAF > 0.01) summary statistics for y_lab and y_hat_lab?  

Best,
Jiacheng

**Comment by robchiral** [comment]
Thanks Jiacheng, this seems to fix it - just to clarify, if below are the bivariate LDSC results, r is 0.3398 (the value for "Intercept")?

Genetic Covariance
------------------
Total Observed scale gencov: 0.0889 (0.01)
Mean z1*z2: 0.4131
Intercept: 0.3398 (0.0032)

Genetic Correlation
-------------------
Genetic Correlation: 0.7387 (0.0649)
Z-score: 11.3729
P: 5.7064e-30

**Comment by jmiao24** [comment]
Yes, that's correct!
