### ISSUE TITLE
environment.yml not found

### ISSUE THREAD

**Issue by ChristianDina** [qlu-lab/POP-TOOLS#4]
Dear collegaues,
congratulations for your paper. I am trying to run the tool you are proposing and find this error :
**EnvironmentFileNotFound: '/../POP-TOOLS/environment.yml' file not found**

Best regards

Christian

**Comment by jmiao24** [comment]
Hi Christian,

Thank you!  I have uploaded the `environment.yml` file to GitHub. Please also update POP-TOOLS to the latest version for use.

Best,
Jiacheng

**Comment by ChristianDina** [comment]
> Hi Christian,
> 
> Thank you! I have uploaded the `environment.yml` file to GitHub. Please also update POP-TOOLS to the latest version for use.
> 
> Best, Jiacheng

Thanks a lot. Will try ...

**Comment by ChristianDina** [comment]
The example (WXD) worked. I still need to figure out how to create our yhat and unlabeled stuff (while I sort of understand the principle, I need to see how to make it). Thanks
